import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/globals.css";
import { Header } from "@/components/header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function PublicLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			lang="pt-BR"
			className="w-full h-full"
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased w-full min-h-screen flex flex-col`}
			>
				<Header />
				<main className="flex-1 flex justify-center items-center">{children}</main>
			</body>
		</html>
	);
}
